# Generated by Django 2.2.1 on 2019-05-16 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodTypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('isDelete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GoodInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtittle', models.CharField(max_length=32)),
                ('gpic', models.ImageField(upload_to='goods')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('guntil', models.CharField(default='500g', max_length=10)),
                ('isDelete', models.BooleanField(default=0)),
                ('gclick', models.IntegerField()),
                ('gintroduction', models.CharField(max_length=250)),
                ('stock', models.IntegerField()),
                ('gcontent', models.CharField(max_length=800)),
                ('gadv', models.BooleanField(default=0)),
                ('gtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodTypeInfo')),
            ],
        ),
    ]
