# Generated by Django 2.2.1 on 2019-06-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190516_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodinfo',
            old_name='gtittle',
            new_name='gtitle',
        ),
    ]
