# Generated by Django 2.2.1 on 2019-06-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190606_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodinfo',
            name='gcontent',
            field=models.TextField(blank=True),
        ),
    ]
