# Generated by Django 2.2.1 on 2019-06-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190610_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodinfo',
            name='gclick',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goodinfo',
            name='gpic',
            field=models.ImageField(upload_to='image/goods'),
        ),
        migrations.AlterField(
            model_name='goodinfo',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
