# Generated by Django 2.2.1 on 2019-05-13 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uname', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('upassword', models.CharField(max_length=30)),
                ('phone', models.CharField(default='', max_length=11)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_adress', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manage.UserInfo')),
            ],
        ),
    ]
