# Generated by Django 2.2.1 on 2019-06-06 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradress',
            name='user',
        ),
        migrations.AddField(
            model_name='useradress',
            name='r_phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='useradress',
            name='r_user',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useradress',
            name='zipcode',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='addressee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_manage.UserAdress'),
        ),
    ]
